spring:
  profiles:
    active:
      - dev
      
---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept-dev

---

server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-dept-test


